/**
 * PublicationContentPart2.ts
 * 
 * Design, Multimedia, AI, Productivity & Freelancing Tracks:
 * Graphics Design, UI/UX, Video Editing, Mobile App Development, AI & Automation,
 * Microsoft Office Productivity, Freelancing (Upwork/Fiverr), and Career Planning Workbook.
 */

import { PublicationHelper as H } from './PublicationHelper.ts';

export class PublicationContentPart2 {
  public static generate(titleLower: string, catLower: string, title: string, category: string): string | null {
    // 9. Graphics Design Starter Guide
    if (titleLower.includes("graphics design") || titleLower.includes("graphic design") || catLower.includes("graphic")) {
      return [
        H.buildCoverPage("Professional Graphics & Brand Identity Design Guide", "Mastering Visual Communication, Typography Hierarchy, Color Theory & Vector/Raster Workflows", "Brand & Multimedia Design"),
        H.buildTableOfContents([
          { id: "1-core-principles-of-visual-design", title: "Core Principles of Visual Design" },
          { id: "2-essential-software--workflow-mastery", title: "Essential Software & Workflow Mastery (Figma, Illustrator, Photoshop)" },
          { id: "3-social-media-asset-production-guidelines", title: "Social Media Asset Production Guidelines" },
          { id: "4-typography-pairing--color-psychology-matrix", title: "Typography Pairing & Color Psychology Matrix" },
          { id: "5-practical-before--after-design-transformations", title: "Practical Before & After Design Transformations" },
          { id: "6-interactive-brand-identity-audit-checklist", title: "Interactive Brand Identity Audit Checklist" },
          { id: "7-closing-advice-learning-path--contact", title: "Closing Advice, Learning Path & Contact" }
        ]),
        "## 1. Core Principles of Visual Design",
        "",
        "* **Hierarchy:** Guiding the viewer's eye through size, weight, color contrast, and spatial placement. The most critical message must command instant attention.",
        "* **Typography & Pairing:**.",
        "  * **Sans-Serif (Modern / Tech):** Inter, Space Grotesk, Montserrat, Helvetica. Ideal for UI headers and digital flyers.",
        "  * **Serif (Editorial / Elegant):** Playfair Display, Merriweather, Garamond. Ideal for formal invitations and luxury branding.",
        "  * **Rule of Thumb:** Never use more than 2 font families in a single layout. Use varying weights (Regular, Semi-Bold, Black) for contrast.",
        "* **Color Theory & Psychology:**.",
        "  * **60-30-10 Rule:** 60% dominant background color, 30% secondary brand color, 10% high-contrast accent/action color.",
        "  * **Color Modes:** Always design in **RGB** for digital screens (web, social media) and **CMYK** (300 DPI minimum) for physical print (banners, brochures, business cards).",
        "",
        H.buildDiagramPlaceholder("Illustration", "The 60-30-10 Color Dominance Ratio & Spatial Grid Composition"),
        "",
        "---",
        "",
        "## 2. Essential Software & Workflow Mastery (Figma, Illustrator, Photoshop)",
        "",
        "* **Figma (Vector Design & UI/Layouts):**.",
        "  * Auto-Layout frames, constraints, reusable components, and typography styles.",
        "  * Exporting vector SVG icons and high-resolution PNG marketing banners.",
        "* **Adobe Illustrator (Vector Logo & Branding):**.",
        "  * Pen tool precision, Pathfinder boolean operations, creating scalable brand marks without pixelation.",
        "* **Adobe Photoshop (Raster Editing & Photo Manipulation):**.",
        "  * Non-destructive editing using adjustment layers and layer masks.",
        "  * Smart Objects, background removal, color grading, and social media mockup presentation.",
        "",
        H.buildCallout("tip", "Always work destructively! When editing photos in Photoshop, use Layer Masks instead of the Eraser tool so you can restore original pixels whenever a client changes their mind."),
        "",
        "---",
        "",
        "## 3. Social Media Asset Production Guidelines",
        "",
        "* **Instagram / Facebook Square Post:** 1080 x 1080 px (1:1 ratio).",
        "* **Instagram / TikTok Story & Reel Cover:** 1080 x 1920 px (9:16 vertical ratio).",
        "* **LinkedIn Banner / Corporate Header:** 1584 x 396 px.",
        "* **YouTube Video Thumbnail:** 1280 x 720 px (16:9 ratio, high contrast, bold readable text at small scales).",
        "* **Export Standards:** Export PNG-24 for crisp text graphics and vector logos; use JPEG (85% quality) for photographic layouts to optimize file size.",
        "",
        "---",
        "",
        "## 4. Typography Pairing & Color Psychology Matrix",
        "",
        H.buildComparisonTable(
          ["Brand Vibe / Aesthetic", "Recommended Font Pairing (Header + Body)", "Optimal Color Palette Psychology"],
          [
            ["Corporate Tech & SaaS", "Space Grotesk (Bold) + Inter (Regular)", "Deep Slate Blue (#0f172a), Crisp White, Vibrant Electric Blue accent"],
            ["Luxury & Editorial", "Playfair Display (Serif) + Lato (Sans-Serif)", "Rich Charcoal, Cream/Ivory background, Subtle Gold/Ochre accents"],
            ["Eco & Sustainability", "Montserrat (Semi-Bold) + Open Sans (Regular)", "Forest Green (#065f46), Earthy Tan, Soft Sage Green background"],
            ["Fintech & Enterprise Security", "Outfit (Bold) + Plus Jakarta Sans (Regular)", "Navy Blue, Dark Emerald Green accent, Clean Light Gray canvas"]
          ]
        ),
        "",
        "## 5. Practical Before & After Design Transformations",
        "",
        H.buildPracticalExample(
          "Flyer Headline Composition",
          "Placing 5 different fonts in bright yellow text over a busy un-darkened photograph.",
          "Using 2 clean fonts aligned to the center with a basic solid box behind the text.",
          "Applying a 40% black gradient overlay to the hero photograph, pairing left-aligned Space Grotesk Bold headers in crisp white with a single electric green call-to-action button adhering to the 8px baseline grid."
        ),
        "",
        "## 6. Interactive Brand Identity Audit Checklist",
        "",
        H.buildChecklist("Design Quality Assurance Audit", [
          { label: "Vector Scalability Verified", desc: "Logo and iconography are drawn in Figma/Illustrator vectors and can scale infinitely without pixelation." },
          { label: "Contrast Ratio Compliant", desc: "Text color against background achieves at least a 4.5:1 contrast ratio for effortless readability." },
          { label: "Maximum 2 Font Families", desc: "Layout uses no more than two distinct font families, utilizing weights (Bold/Regular) for hierarchy." },
          { label: "Proper Export Color Mode", desc: "Digital social media assets are exported in RGB; physical banner artwork is configured in CMYK at 300 DPI." }
        ]),
        "",
        H.buildClosingPage(title)
      ].join("\n");
    }

    // 10. UI/UX Starter Guide
    if (titleLower.includes("ui/ux") || titleLower.includes("ui ux") || titleLower.includes("user interface") || catLower.includes("ui/ux")) {
      return [
        H.buildCoverPage("UI/UX Design & Product Research Starter Guide", "Designing Intuitive, Accessible, and High-Converting Digital Experiences • Figma & Design Thinking", "UI/UX & Product Design"),
        H.buildTableOfContents([
          { id: "1-the-design-thinking--user-research-process", title: "The Design Thinking & User Research Process" },
          { id: "2-wireframing--prototyping-in-figma", title: "Wireframing & Prototyping in Figma" },
          { id: "3-web--mobile-usability-principles-nielsens-10-heuristics", title: "Web & Mobile Usability Principles (Nielsen's 10 Heuristics)" },
          { id: "4-web-accessibility-standards-wcag-21-compliance", title: "Web Accessibility Standards (WCAG 2.1 Compliance)" },
          { id: "5-uiux-design-system-tokenization-matrix", title: "UI/UX Design System Tokenization Matrix" },
          { id: "6-interactive-usability--accessibility-checklist", title: "Interactive Usability & Accessibility Checklist" },
          { id: "7-closing-advice-learning-path--contact", title: "Closing Advice, Learning Path & Contact" }
        ]),
        "## 1. The Design Thinking & User Research Process",
        "",
        "Great UI is useless if it solves the wrong user problem. Follow the 5-stage Design Thinking framework:",
        "1. **Empathize:** Conduct user interviews, observe user frustrations, and analyze support tickets to understand actual user needs.",
        "2. **Define:** Create User Personas (e.g., *\"Amina, a 24-year-old NYSC Corp Member needing quick offline access to her transport manifest\"*). Define precise Problem Statements.",
        "3. **Ideate:** Sketch low-fidelity paper wireframes and explore multiple structural layout approaches without worrying about colors or fonts.",
        "4. **Prototype:** Build interactive, clickable prototypes in Figma connecting user journeys from login to task completion.",
        "5. **Test:** Conduct usability testing sessions with real users. Observe where they stumble without leading them to the answer.",
        "",
        H.buildDiagramPlaceholder("Flowchart", "The 5-Stage Design Thinking Iterative Loop: Empathize -> Define -> Ideate -> Prototype -> Test"),
        "",
        "---",
        "",
        "## 2. Wireframing & Prototyping in Figma",
        "",
        "* **Figma Fundamentals:** Frames vs. Groups, Auto Layout 5.0 (responsive padding, flex-wrapping, spacing), Components, Variants, and Interactive Component states (Hover, Pressed, Disabled).",
        "* **Design Systems & Tokenization:** Setting up reusable typography variables, color tokens (Primary, Secondary, Success, Warning, Neutral Slate), and spacing grids (4px / 8px baseline grid).",
        "* **Interactive Prototyping:** Smart Animate transitions, overlay modals, scrolling carousels, and bottom sheets for mobile device previews.",
        "",
        H.buildCallout("pro_tip", "Never use standard Groups (`Ctrl+G`) for UI layouts in Figma! Always use Auto Layout (`Shift+A`). Auto Layout ensures your padding, margins, and button responsiveness automatically adapt when text length changes."),
        "",
        "---",
        "",
        "## 3. Web & Mobile Usability Principles (Nielsen's 10 Heuristics)",
        "",
        "1. **Visibility of System Status:** Always keep users informed through loading spinners, progress bars, and immediate toast notifications.",
        "2. **Match Between System & Real World:** Use familiar icons (e.g., magnifying glass for search, trash can for delete) and human, jargon-free labels.",
        "3. **User Control & Freedom:** Provide obvious \"Cancel\", \"Back\", and \"Undo\" buttons so users never feel trapped by accidental clicks.",
        "4. **Consistency & Standards:** Buttons that perform the same action should look identical across every page of the application.",
        "5. **Error Prevention & Recovery:** Highlight invalid form inputs with clear inline red error text before the user submits the form.",
        "",
        "---",
        "",
        "## 4. Web Accessibility Standards (WCAG 2.1 Compliance)",
        "",
        "* **Color Contrast Ratio:** Ensure normal body text has a minimum contrast ratio of **4.5:1** against its background (use tools like Stark or WebAIM Contrast Checker).",
        "* **Touch Target Size:** Interactive mobile buttons and links must be at least **44 x 44 pixels** to prevent accidental misclicks.",
        "* **Keyboard Navigation:** Ensure every form field and button can be reached and activated using `Tab` and `Enter` without requiring a mouse.",
        "",
        "---",
        "",
        "## 5. UI/UX Design System Tokenization Matrix",
        "",
        H.buildComparisonTable(
          ["Design Token Category", "Hardcoded / Sloppy Approach (Avoid)", "Gold Master Tokenized System (Use)"],
          [
            ["Color Palette", "Random hex codes scattered everywhere (#3b82f6, #2563eb)", "Semantic Color Tokens (`--color-primary-600`, `--color-surface-slate`)"],
            ["Spacing Grid", "Arbitrary pixel padding (13px, 17px, 22px)", "Strict 4px/8px Baseline Spacing Scale (`4px, 8px, 16px, 24px, 32px`)"],
            ["Typography Scale", "Random font sizes (14.5px, 18px, 23px)", "Modular Type Scale (`text-sm`, `text-base`, `text-lg`, `text-2xl`)"],
            ["Component States", "Only designing the default static state of a button", "Designing all 5 states: Default, Hover, Active/Pressed, Disabled, Loading"]
          ]
        ),
        "",
        "## 6. Interactive Usability & Accessibility Checklist",
        "",
        H.buildChecklist("Figma UI/UX Ready-for-Dev Inspection", [
          { label: "100% Auto-Layout Utilized", desc: "All cards, buttons, and navigation bars use Figma Auto-Layout without static coordinate dragging." },
          { label: "4.5:1 Contrast Ratio Tested", desc: "Text foreground against background color passes WCAG AA accessibility standards." },
          { label: "44x44px Touch Targets Enforced", desc: "All mobile clickable icons and buttons meet the minimum touch target bounding box dimensions." },
          { label: "Error States Defined", desc: "Form input mockups clearly show both default neutral states and inline validation error styles." },
          { label: "Component Library Cleaned", desc: "All buttons and cards are extracted as reusable Master Components with clean Variant naming." }
        ]),
        "",
        H.buildClosingPage(title)
      ].join("\n");
    }

    // 11. Video Editing Starter Guide
    if (titleLower.includes("video editing") || titleLower.includes("video editor") || catLower.includes("video")) {
      return [
        H.buildCoverPage("Professional Video Editing & Post-Production Starter Guide", "Mastering Timeline Workflow, Pacing, Color Grading, Audio Mixing & Broadcast Export Standards", "Video & Multimedia Production"),
        H.buildTableOfContents([
          { id: "1-the-post-production-workflow-pipeline", title: "The Post-Production Workflow Pipeline" },
          { id: "2-essential-shortcuts--software-proficiency", title: "Essential Shortcuts & Software Proficiency" },
          { id: "3-social-media--broadcast-export-specifications", title: "Social Media & Broadcast Export Specifications" },
          { id: "4-audio-mixing--color-grading-standards", title: "Audio Mixing & Color Grading Standards" },
          { id: "5-video-editing-software-comparison-matrix", title: "Video Editing Software Comparison Matrix" },
          { id: "6-interactive-post-production-checklist", title: "Interactive Post-Production Checklist" },
          { id: "7-closing-advice-learning-path--contact", title: "Closing Advice, Learning Path & Contact" }
        ]),
        "## 1. The Post-Production Workflow Pipeline",
        "",
        "To edit efficiently without losing files or crashing software, follow a structured workflow:",
        "1. **Project Organization:** Create folders before importing: `/01_Footage`, `/02_Audio_Music`, `/03_Sound_Effects_SFX`, `/04_Graphics_Logos`, `/05_Exports`.",
        "2. **Assembly & Rough Cut (The A-Cut):** Review all raw clips. Mark In (`I`) and Out (`O`) points on usable takes and drop them onto the primary timeline sequence. Cut out dead air, mistakes, and false starts.",
        "3. **Fine Cut & Pacing:** Adjust clip durations to match the rhythm of the voiceover or background music beat. Ensure eye-lines and motion continuity flow naturally between scene transitions.",
        "4. **B-Roll & Visual Enrichment:** Overlay supporting B-roll footage, screen recordings, text titles, lower thirds, and callout graphics over the A-roll interview voice track.",
        "5. **Color Correction & Grading:**.",
        "   * **Color Correction:** Balance exposure, white balance, and skin tones so all camera shots look unified and natural.",
        "   * **Color Grading:** Apply creative LUTs or contrast curves to establish emotional mood (e.g., warm cinematic teal/orange vs. crisp tech corporate blue).",
        "6. **Audio Mixing & Sound Design:**.",
        "   * Balance voice tracks to **-6 dB to -12 dB** (clear and crisp, never peaking above 0 dB).",
        "   * Duck background music down to **-22 dB to -28 dB** beneath dialogue.",
        "   * Add subtle Foley sound effects (whooshes, clicks, keyboard typing) to enhance visual transitions.",
        "",
        H.buildDiagramPlaceholder("Diagram", "Non-Linear Video Timeline Layering: Video Tracks (V1-V3) vs. Audio Tracks (A1-A3)"),
        "",
        "---",
        "",
        "## 2. Essential Shortcuts & Software Proficiency",
        "",
        "* **Adobe Premiere Pro / DaVinci Resolve Essential Shortcuts:**.",
        "  * `C` / `Razor Tool` (Cut clip at playhead position).",
        "  * `V` / `Selection Tool` (Move and arrange timeline segments).",
        "  * `Q` / `Ripple Trim Previous Edit` (Instantly delete dead space to the left of playhead).",
        "  * `W` / `Ripple Trim Next Edit` (Instantly delete dead space to the right of playhead).",
        "  * `M` / `Add Marker` (Mark music beats or key transition moments on timeline).",
        "",
        H.buildCallout("tip", "Mastering Ripple Trim (`Q` and `W`) will double your rough-cutting speed! Instead of cutting with the razor tool and manually deleting the empty gap, ripple trim cuts and closes the gap in a single keystroke."),
        "",
        "---",
        "",
        "## 3. Social Media & Broadcast Export Specifications",
        "",
        "* **YouTube Master (High Quality 4K / 1080p):** Codec: H.264 / H.265 (HEVC), Container: MP4, Resolution: 1920x1080 or 3840x2160 (16:9 ratio), Frame Rate: Match source (24 fps cinematic or 30/60 fps tech tutorial), Target Bitrate: 15–25 Mbps for 1080p, Audio: AAC 320 kbps Stereo.",
        "* **TikTok / Instagram Reel / YouTube Short:** Resolution: 1080x1920 px (9:16 vertical), Frame Rate: 30 fps or 60 fps, Max Duration: 60 seconds (optimize hook in first 3 seconds with dynamic captions).",
        "",
        "---",
        "",
        "## 4. Audio Mixing & Color Grading Standards",
        "",
        "Hiring managers and viewers will tolerate mediocre video quality, but they will instantly abandon a video with bad or echoing audio. Always prioritize audio clarity.",
        "",
        "---",
        "",
        "## 5. Video Editing Software Comparison Matrix",
        "",
        H.buildComparisonTable(
          ["Editing Application", "Core Strengths & Specialization", "Target User & Industry Standard"],
          [
            ["Adobe Premiere Pro", "Industry standard editing, seamless integration with After Effects", "Corporate video teams, marketing agencies, YouTube creators"],
            ["DaVinci Resolve", "World-class node-based color grading, Fairlight audio mixing, free tier", "Cinematographers, professional colorists, independent editors"],
            ["CapCut Desktop", "Ultra-fast auto-captions, trending transitions, built-in TikTok effects", "Short-form social media marketers, TikTok/Reels content creators"],
            ["Final Cut Pro", "Ultra-fast magnetic timeline, optimized Apple silicon M-series rendering", "Mac-based journalists, wedding videographers, fast-turnaround editors"]
          ]
        ),
        "",
        "## 6. Interactive Post-Production Checklist",
        "",
        H.buildChecklist("Video Export Quality Assurance Protocol", [
          { label: "Zero Audio Peaking (Red Zone)", desc: "Dialogue tracks peak cleanly between -6 dB and -12 dB without distortion." },
          { label: "Music Ducked Beneath Dialogue", desc: "Background tracks drop to -24 dB during voiceover and swell during transitions." },
          { label: "Color Correction Normalized", desc: "Skin tones look natural and white balance matches seamlessly across A-roll and B-roll cuts." },
          { label: "No Flash/Glitch Frames", desc: "Timeline inspected zoom-level 100% to ensure zero 1-frame black gaps between clips." },
          { label: "Target Aspect Ratio Exported", desc: "Video exported cleanly in MP4 H.264 matching intended destination (16:9 YouTube vs. 9:16 Reels)." }
        ]),
        "",
        H.buildClosingPage(title)
      ].join("\n");
    }

    // 12. App Development Starter Guide
    if (titleLower.includes("app development") || titleLower.includes("mobile app") || catLower.includes("app dev") || catLower.includes("mobile")) {
      return [
        H.buildCoverPage("Mobile App Development Roadmap & Architecture Guide", "Building Cross-Platform iOS & Android Applications • React Native, Flutter & Offline-First Sync", "Mobile Engineering"),
        H.buildTableOfContents([
          { id: "1-choosing-your-mobile-development-stack", title: "Choosing Your Mobile Development Stack" },
          { id: "2-core-mobile-architecture--state-management", title: "Core Mobile Architecture & State Management" },
          { id: "3-offline-first-storage--cloud-synchronization", title: "Offline-First Storage & Cloud Synchronization" },
          { id: "4-app-store-deployment--release-sop", title: "App Store Deployment & Release SOP" },
          { id: "5-mobile-framework-comparison-matrix", title: "Mobile Framework Comparison Matrix" },
          { id: "6-interactive-mobile-app-release-checklist", title: "Interactive Mobile App Release Checklist" },
          { id: "7-closing-advice-learning-path--contact", title: "Closing Advice, Learning Path & Contact" }
        ]),
        "## 1. Choosing Your Mobile Development Stack",
        "",
        "* **React Native (TypeScript / JavaScript):**.",
        "  * **Why Choose It:** If you already know web development (React, Node.js), React Native allows you to share up to 90% of your codebase across iOS, Android, and Web using native UI bridges.",
        "  * **Key Tools:** Expo SDK, React Navigation, NativeWind (Tailwind for mobile), Reanimated 3 for smooth 60fps UI animations.",
        "* **Flutter (Dart Language):**.",
        "  * **Why Choose It:** Powered by Google's Skia graphics engine, Flutter compiles directly to ARM machine code, delivering ultra-high performance and pixel-perfect UI consistency across all devices.",
        "  * **Key Tools:** Riverpod / Bloc state management, Material 3 & Cupertino widgets, Flutter DevTools for memory profiling.",
        "* **Native Development (When Required):**.",
        "  * **Android (Kotlin + Jetpack Compose):** Use when building hardware-intensive apps requiring low-level Bluetooth, NFC, or heavy background sensor processing.",
        "  * **iOS (Swift + SwiftUI):** Use when targeting Apple ecosystem exclusive features (ARKit, HealthKit, WidgetKit).",
        "",
        H.buildDiagramPlaceholder("Diagram", "Cross-Platform Bridge Architecture: JavaScript Realm <-> Native Bridge <-> OS Android/iOS UI Threads"),
        "",
        "---",
        "",
        "## 2. Core Mobile Architecture & State Management",
        "",
        "* **Navigation Architecture:** Stack Navigation (pushing/popping screens), Tab Navigation (bottom bar navigation), and Drawer Navigation (side menu). Always handle deep linking (`corpersapp://manifest/123`).",
        "* **Hardware & Sensor Integration:** Requesting OS runtime permissions cleanly (Camera for QR scanning, GPS Geolocation for shuttle tracking, Push Notifications via Firebase Cloud Messaging / APNS).",
        "",
        "---",
        "",
        "## 3. Offline-First Storage & Cloud Synchronization",
        "",
        "Mobile apps frequently experience network drops in transit. Use local persistence engines (**MMKV**, **SQLite**, **WatermelonDB**, or **AsyncStorage**) to cache user data locally before syncing to cloud REST APIs.",
        "",
        H.buildCallout("best_practice", "Always design your mobile apps assuming the network is slow or disconnected. Implement optimistic UI updates and local SQLite caching so users can view their manifests and logs even when underground or out of data coverage."),
        "",
        "---",
        "",
        "## 4. App Store Deployment & Release SOP",
        "",
        "1. **App Bundling & Signing:**.",
        "   * Android: Generate an upload Keystore (.jks), configure `build.gradle` signing configs, and build an **Android App Bundle (.aab)** for Google Play Console.",
        "   * iOS: Manage Apple Developer provisioning profiles, certificates in Xcode, and archive iOS build builds for TestFlight and App Store Connect.",
        "2. **Store Listing Metadata:** Prepare high-resolution screenshots (6.5\" iPhone and 10\" Tablet), clear concise descriptions, privacy policy URLs, and content rating questionnaires.",
        "",
        "---",
        "",
        "## 5. Mobile Framework Comparison Matrix",
        "",
        H.buildComparisonTable(
          ["Mobile Tech Stack", "Primary Language & Performance", "Best Match for Corporate / Student Developer"],
          [
            ["React Native (Expo)", "TypeScript / JS (High performance with Reanimated 3)", "Web developers wanting fastest transition to iOS/Android apps"],
            ["Flutter", "Dart (Ultra-fast ARM machine code rendering)", "Teams needing pixel-perfect custom visual widgets across platforms"],
            ["Kotlin (Android Native)", "Kotlin / Jetpack Compose (Maximum native device OS speed)", "Engineers building low-level hardware or Bluetooth sensor apps"],
            ["SwiftUI (iOS Native)", "Swift (Maximum Apple ecosystem performance)", "Dedicated iOS engineers building Apple-exclusive software"]
          ]
        ),
        "",
        "## 6. Interactive Mobile App Release Checklist",
        "",
        H.buildChecklist("App Store & Play Store Readiness Protocol", [
          { label: "App Bundle (.aab) Signed Cleanly", desc: "Android release build signed with production upload keystore; passwords saved in secure vault." },
          { label: "Runtime Permissions Handled Gracefully", desc: "Camera and location prompts explain why permission is needed before triggering OS system dialog." },
          { label: "Offline Mode Tested", desc: "App tested in Airplane Mode; cached data loads cleanly without app crash or white screen." },
          { label: "App Store Screenshots Generated", desc: "High-resolution device mockups exported matching exact Apple and Google required dimensions." },
          { label: "Privacy Policy URL Accessible", desc: "Live HTTPS link to company privacy policy is active and submitted in store console." }
        ]),
        "",
        H.buildClosingPage(title)
      ].join("\n");
    }

    // 13. AI & Automation Learning Guide
    if (titleLower.includes("ai ") || titleLower.includes("automation") || titleLower.includes("gemini") || catLower.includes("ai") || catLower.includes("automation")) {
      return [
        H.buildCoverPage("AI Engineering & Workflow Automation Playbook", "Mastering Prompt Engineering, LLM APIs (Gemini 2.5/3.0), and Autonomous Agent Workflows", "AI Engineering & Automation"),
        H.buildTableOfContents([
          { id: "1-advanced-prompt-engineering-fundamentals", title: "Advanced Prompt Engineering Fundamentals" },
          { id: "2-integrating-google-gemini-api-in-typescript--nodejs", title: "Integrating Google Gemini API in TypeScript / Node.js" },
          { id: "3-workflow-automation-engines-make--zapier--python", title: "Workflow Automation Engines (Make / Zapier / Python)" },
          { id: "4-retrieval-augmented-generation-rag-architecture", title: "Retrieval-Augmented Generation (RAG) Architecture" },
          { id: "5-ai-model--automation-tool-matrix", title: "AI Model & Automation Tool Matrix" },
          { id: "6-interactive-ai-project-deployment-checklist", title: "Interactive AI Project Deployment Checklist" },
          { id: "7-closing-advice-learning-path--contact", title: "Closing Advice, Learning Path & Contact" }
        ]),
        "## 1. Advanced Prompt Engineering Fundamentals",
        "",
        "To get reliable, production-grade output from Large Language Models, structure your prompts using the **4-Pillar Context Architecture**:.",
        "1. **Persona & Role Definition:** *\"You are an expert Senior Cybersecurity Analyst and technical writer at Olatech School of Programming.\"*",
        "2. **Task & Explicit Scope:** *\"Analyze the following server nginx error log snippet. Identify potential SQL injection or brute force patterns and recommend 3 immediate containment rules.\"*",
        "3. **Input Data / Grounding Context:** Provide structured JSON or plain-text logs enclosed in clear markdown delimiters (```log ... ```).",
        "4. **Output Format & Constraints:** *\"Return your answer strictly as a valid JSON object with keys: `severity`, `threatType`, `affectedIP`, and `actionPlan`. Do not include conversational introductory text.\"*",
        "",
        H.buildDiagramPlaceholder("Flowchart", "RAG Pipeline: User Prompt -> Embeddings -> Vector DB -> Context Injection -> Gemini API Response"),
        "",
        "---",
        "",
        "## 2. Integrating Google Gemini API in TypeScript / Node.js",
        "",
        "Always execute AI calls server-side (`server.ts`) to prevent API key leakage in browser devtools.",
        "",
        "### Code Pattern (Using `@google/genai` Modern SDK):.",
        "```typescript",
        "import { GoogleGenAI } from \"@google/genai\";",
        "",
        "// Initialize lazy client server-side",
        "const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });",
        "",
        "export async function analyzeStudentCV(cvText: string, targetRole: string) {",
        "  try {",
        "    const response = await ai.models.generateContent({",
        "      model: \"gemini-2.5-flash\", // Fast, highly capable model for text analysis",
        "      contents: [",
        "        {",
        "          role: \"user\",",
        "          parts: [{",
        "            text: `Evaluate this CV against the role of ${targetRole}. Provide an ATS score (0-100) and 3 actionable improvement tips.\\n\\nCV TEXT:\\n${cvText}`",
        "          }]",
        "        }",
        "      ],",
        "      config: {",
        "        systemInstruction: \"You are an institutional Career Coach at Olatech School of Programming. Be constructive, objective, and precise.\",",
        "        temperature: 0.3, // Low temperature for consistent, analytical output",
        "      }",
        "    });",
        "    return response.text;",
        "  } catch (error) {",
        "    console.error(\"Gemini API execution failed:\", error);",
        "    throw new Error(\"Failed to compute AI evaluation. Please check server logs.\");",
        "  }",
        "}",
        "```",
        "",
        "---",
        "",
        "## 3. Workflow Automation Engines (Make / Zapier / Python)",
        "",
        "* **Automating Recruitment Pipelines:** Connect Google Forms / Tally enrollment forms to Webhook triggers → run data validation script → push structured candidate lead to PostgreSQL database → trigger automated welcoming WhatsApp / SMS notification via Twilio / Termii API.",
        "* **Daily Report Generation:** Configure background cron jobs (`0 0 * * *`) to aggregate SQLite/Prisma daily student attendance metrics → summarize via Gemini API → dispatch executive markdown summary email to Olatech Directors automatically.",
        "",
        "---",
        "",
        "## 4. Retrieval-Augmented Generation (RAG) Architecture",
        "",
        "When building chatbots that answer questions about private institutional handbooks or databases, never rely on standard LLM training memory! Implement RAG: convert your documents into vector embeddings using `text-embedding-004`, store them in a vector store, retrieve matching chunks on user query, and inject them into the Gemini system prompt.",
        "",
        "---",
        "",
        "## 5. AI Model & Automation Tool Matrix",
        "",
        H.buildComparisonTable(
          ["AI Model / Automation Platform", "Optimal Technical Use Case", "Why It Beats Legacy Alternatives"],
          [
            ["Gemini 2.5 Flash (`@google/genai`)", "High-throughput text analysis, JSON extraction, code reviews", "Ultra-low latency, massive 1M token context window, cost-effective"],
            ["Gemini 2.5 Pro", "Deep reasoning, complex architectural synthesis, mathematics", "Unmatched analytical precision for complex multi-step instructions"],
            ["Python + Playwright Automation", "Scraping job boards and automating repetitive web data entry", "Open-source, highly customizable, zero monthly SaaS automation subscription fees"],
            ["Make.com / n8n Automation Workflows", "No-code / Low-code API integration pipelines", "Visual drag-and-drop webhooks connecting Google Sheets, Slack, and APIs"]
          ]
        ),
        "",
        "## 6. Interactive AI Project Deployment Checklist",
        "",
        H.buildChecklist("AI Production Readiness Verification", [
          { label: "API Keys Kept Server-Side", desc: "Gemini API key is accessed via server environment variables, never exposed in client bundle." },
          { label: "Temperature Configured Correctly", desc: "Analytical tasks set to low temperature (0.1–0.3); creative content generation set to 0.7–0.8." },
          { label: "JSON Output Schema Validated", desc: "Structured AI responses are parsed and verified using Zod schemas before rendering in UI." },
          { label: "Rate Limiting & Error Fallbacks", desc: "API failure blocks include exponential backoff retries and user-friendly fallback notices." },
          { label: "System Instruction Guardrails Set", desc: "Model persona rules strictly prohibit answering out-of-scope queries or generating toxic content." }
        ]),
        "",
        H.buildClosingPage(title)
      ].join("\n");
    }

    // 14. Microsoft Office Productivity Guide
    if (titleLower.includes("microsoft office") || titleLower.includes("excel") || titleLower.includes("word") || titleLower.includes("powerpoint") || catLower.includes("office") || catLower.includes("productivity")) {
      return [
        H.buildCoverPage("Microsoft Office & Workplace Productivity Master Guide", "Essential Excel Financial Modeling, Word Corporate Formatting & PowerPoint Storytelling Architecture", "Corporate Productivity"),
        H.buildTableOfContents([
          { id: "1-microsoft-excel-advanced-financial--operational-mastery", title: "Microsoft Excel Advanced Financial & Operational Mastery" },
          { id: "2-microsoft-word-document-formatting--corporate-templates", title: "Microsoft Word Document Formatting & Corporate Templates" },
          { id: "3-microsoft-powerpoint-presentation--storytelling-architecture", title: "Microsoft PowerPoint Presentation & Storytelling Architecture" },
          { id: "4-corporate-office-shortcut-mastery-matrix", title: "Corporate Office Shortcut Mastery Matrix" },
          { id: "5-practical-before--after-office-transformations", title: "Practical Before & After Office Transformations" },
          { id: "6-interactive-corporate-document-checklist", title: "Interactive Corporate Document Checklist" },
          { id: "7-closing-advice-learning-path--contact", title: "Closing Advice, Learning Path & Contact" }
        ]),
        "## 1. Microsoft Excel Advanced Financial & Operational Mastery",
        "",
        "* **Essential Shortcuts:** `Ctrl + Arrow Keys` (Jump to edge of data table), `Ctrl + Shift + L` (Toggle table filters), `Alt + =` (Auto-sum selected cells), `F4` (Lock cell reference / Absolute reference `$A$1`).",
        "* **Lookup Formulas:**.",
        "  * **XLOOKUP (The Modern King):** `=XLOOKUP(lookup_value, lookup_array, return_array, \"Not Found\", 0)` — Replaces VLOOKUP and HLOOKUP; searches in any direction without breaking when columns are inserted.",
        "  * **INDEX / MATCH:** `=INDEX(Return_Range, MATCH(Lookup_Val, Lookup_Range, 0))` — Power combination for complex legacy spreadsheets.",
        "* **Data Summarization:** Building dynamic **Pivot Tables**, calculated fields, grouping dates by Month/Quarter, and designing interactive dashboard slicers for management reporting.",
        "",
        H.buildDiagramPlaceholder("Diagram", "Excel Financial Ledger Architecture: Raw Data Tab -> Pivot Engine -> Executive Summary Dashboard"),
        "",
        "---",
        "",
        "## 2. Microsoft Word Document Formatting & Corporate Templates",
        "",
        "* **Styles & Hierarchy:** Never format headings manually by changing font size and color! Always modify and apply built-in **Styles** (*Normal, Heading 1, Heading 2, Heading 3*). This automatically generates clickable Table of Contents and ensures document-wide formatting consistency.",
        "* **Section Breaks & Headers:** Using *Next Page Section Breaks* (`Layout > Breaks > Next Page`) to unlink headers and footers between title pages, executive summaries, and multi-column appendices.",
        "* **Mail Merge Automation:** Linking Excel student contact spreadsheets to Word letters or email templates to generate thousands of personalized NYSC placement letters in 3 clicks.",
        "",
        "---",
        "",
        "## 3. Microsoft PowerPoint Presentation & Storytelling Architecture",
        "",
        "* **Slide Master Setup:** Always design your background layouts, logo placement, and typography hierarchy in **Slide Master View** (`View > Slide Master`) before creating individual slides. This prevents logos from jumping around during transitions.",
        "* **6x6 Rule of Thumb:** No more than 6 bullet points per slide, and no more than 6 words per bullet point. Slides should support your verbal pitch, not replace it with a text document.",
        "* **Visual Data Presentation:** Reconsider boring standard pie charts. Use horizontal bar charts sorted in descending order with bold contrast highlighting on the key metric you want executives to remember.",
        "",
        "---",
        "",
        "## 4. Corporate Office Shortcut Mastery Matrix",
        "",
        H.buildComparisonTable(
          ["Office Application", "High-Impact Keyboard Shortcut", "Corporate Productivity Time-Saver"],
          [
            ["Excel", "`Alt + N + V + T` (Insert Pivot Table)", "Instantly summarizes thousands of rows of financial records into structured tables"],
            ["Excel", "`Ctrl + Shift + L` (Toggle Auto-Filter)", "Instantly applies or removes column dropdown filters across active tables"],
            ["Word", "`Ctrl + Alt + 1` / `Ctrl + Alt + 2`", "Instantly applies Heading 1 or Heading 2 styles without clicking ribbon buttons"],
            ["PowerPoint", "`F5` (Start Show) / `Shift + F5` (Start Current)", "Launches presentation instantly from beginning or active working slide"]
          ]
        ),
        "",
        "## 5. Practical Before & After Office Transformations",
        "",
        H.buildPracticalExample(
          "Excel VLOOKUP vs. Modern XLOOKUP",
          "=VLOOKUP(A2, Sheet2!A:E, 4, FALSE) [Breaks instantly if a coworker inserts a new column B]",
          "=INDEX(Sheet2!D:D, MATCH(A2, Sheet2!A:A, 0)) [Robust, but verbose and complex]",
          "=XLOOKUP(A2, Sheet2!A:A, Sheet2!D:D, \"Candidate Not Found\", 0) [100% immune to column insertions, searches left or right, includes custom error fallback]"
        ),
        "",
        "## 6. Interactive Corporate Document Checklist",
        "",
        H.buildChecklist("Workplace Document Standards Audit", [
          { label: "Word Table of Contents Clickable", desc: "Generated automatically from built-in Heading Styles; updates cleanly on page number refresh." },
          { label: "Excel Formulas Lock References ($)", desc: "Absolute references (`$A$1`) applied to tax rates and discount cells before dragging formulas down." },
          { label: "PowerPoint Master Layout Unified", desc: "Corporate logos and footer page numbers are embedded in Slide Master view, not pasted on individual slides." },
          { label: "Zero Broken VLOOKUP Errors (#N/A)", desc: "All formula lookups wrap potential missing values in `IFERROR(...)` or modern `XLOOKUP` fallbacks." }
        ]),
        "",
        H.buildClosingPage(title)
      ].join("\n");
    }

    // 15. Freelancing Guide
    if (titleLower.includes("freelancing") || titleLower.includes("upwork") || titleLower.includes("fiverr") || catLower.includes("freelance")) {
      return [
        H.buildCoverPage("Upwork, Fiverr & Remote Freelancing Master Playbook", "Setting Up High-Converting Profiles, Pricing Strategies, Proposal Scripts & Escrow Protection", "Remote Freelancing & Consulting"),
        H.buildTableOfContents([
          { id: "1-upwork-profile--overview-optimization", title: "Upwork Profile & Overview Optimization" },
          { id: "2-the-4-part-proposal-cover-letter-script", title: "The 4-Part Proposal Cover Letter Script" },
          { id: "3-hourly-vs-fixed-price-billing-strategy", title: "Hourly vs. Fixed-Price Billing Strategy" },
          { id: "4-client-negotiation--red-flag-detection", title: "Client Negotiation & Red Flag Detection" },
          { id: "5-freelance-platform-comparison-matrix", title: "Freelance Platform Comparison Matrix" },
          { id: "6-interactive-freelance-contract-checklist", title: "Interactive Freelance Contract Checklist" },
          { id: "7-closing-advice-learning-path--contact", title: "Closing Advice, Learning Path & Contact" }
        ]),
        "## 1. Upwork Profile & Overview Optimization",
        "",
        "Your Upwork overview must establish immediate trust and specialization. Do not list 15 unrelated skills (e.g., *\"Web Dev, Logo Design, Data Entry, and Video Editing\"*). Generalists earn minimum wage; specialists earn premium hourly rates.",
        "",
        "### The Winning Overview Blueprint:.",
        "```text",
        "⚡ HIgh-Performance Full-Stack Software Engineer & API Specialist ⚡",
        "",
        "Are you struggling with slow web page loading speeds, broken database queries, or need a clean React/TypeScript web application built from scratch without technical debt? ",
        "",
        "I am a certified Full-Stack Developer trained at Olatech School of Programming, specializing in helping tech agencies and businesses architect scalable, responsive web applications using:",
        "✔️ React.js, Next.js, and TypeScript for responsive, accessible frontend interfaces",
        "✔️ Node.js, Express, and PostgreSQL for secure, high-throughput backend APIs",
        "✔️ Custom API integrations (Stripe, Twilio, OpenAI/Gemini AI, Google Maps)",
        "",
        "🎯 Why Work With Me?",
        "1. Clean, Documented Code: I follow strict Git best practices and write self-documenting code that your future team can easily maintain.",
        "2. Clear Daily Communication: I provide daily video/loom progress updates and responsive communication during UTC/GMT business hours.",
        "3. 100% On-Time Delivery Guarantee: I never take on multiple conflicting contracts; your project receives my dedicated focus.",
        "",
        "Let's discuss your project architecture! Click 'Invite to Job' or send a message to start a conversation about your goals today.",
        "```",
        "",
        "---",
        "",
        "## 2. The 4-Part Proposal Cover Letter Script",
        "",
        "When submitting proposals on Upwork or responding to client inquiries, never use generic copy-paste templates. Tailor every proposal using this 4-step framework:",
        "",
        "1. **The Specific Hook (Line 1):** Mention their exact problem and company name from the job description.  ",
        "   👉 *\"Hi [Client Name], I read your project brief regarding the latency issues on your React checkout dashboard and would love to help you resolve them.\"*",
        "2. **The Instant Proof & Diagnosis (Lines 2-3):** Prove you understand the technical root cause immediately.  ",
        "   👉 *\"In my experience with React 18 applications, checkout freeze issues are typically caused by unmemoized state re-renders or blocking synchronous API calls in the useEffect cycle. I recently solved a similar bottleneck for a CRM processing 5,000+ records by implementing Zustand state stabilization and debounced API queries.\"*",
        "3. **Your Proposed Solution Step-by-Step (Bullet points):** Show how you will solve it in the first 48 hours.  ",
        "   👉 *\"If we collaborate, here is my immediate 3-step action plan for Week 1:*  ",
        "   *• Audit your current component tree using React DevTools Profiler.*  ",
        "   *• Refactor the checkout state logic and add clean error boundary fallbacks.*  ",
        "   *• Run automated end-to-end regression tests to verify zero data loss.\"*",
        "4. **The Low-Friction Call to Action (CTA):** Invite a quick chat without pushiness.  ",
        "   👉 *\"I am available to start immediately. Would you be open to a brief 5-minute chat here on Upwork to review your current GitHub repository setup? Best regards, [Your Name].\"*",
        "",
        H.buildCallout("expert", "Always answer client screening questions first! On Upwork mobile apps, clients only see the first 2 lines of your cover letter or your screening answers. Put your most impressive technical metrics right at the very top."),
        "",
        "---",
        "",
        "## 3. Hourly vs. Fixed-Price Billing Strategy",
        "",
        "* **Hourly Projects (Upwork Desktop App):** Always use the official Upwork Desktop Time Tracker with screen caching enabled. This guarantees **Upwork Hourly Payment Protection**, ensuring you get paid even if the client's credit card fails.",
        "* **Fixed-Price Contracts:** **Never begin work without a funded Escrow milestone!** Structure projects into clear milestone deliverables (e.g., Milestone 1: UX Wireframes & Schema Design (30%), Milestone 2: Backend API & Database Setup (40%), Milestone 3: Frontend Integration & Final Testing (30%)).",
        "",
        "---",
        "",
        "## 4. Client Negotiation & Red Flag Detection",
        "",
        "Avoid troublesome clients by watching out for these red flags during initial screening:",
        "* **Red Flag 1:** Client asks to communicate via WhatsApp or Telegram before hiring on Upwork (This violates terms of service and risks permanent account ban).",
        "* **Red Flag 2:** Client refuses to fund Escrow or says *\"I will pay you double after you send me the final source code\"* (High scam risk).",
        "* **Red Flag 3:** Job posting has unverified payment method and zero client review history on large $5,000+ budgets.",
        "",
        "---",
        "",
        "## 5. Freelance Platform Comparison Matrix",
        "",
        H.buildComparisonTable(
          ["Freelance Platform", "Optimal Project Strategy", "Average Hourly / Contract Earning Potential"],
          [
            ["Upwork", "Long-term hourly retainers and structured enterprise contracts", "$25 – $85+ / hr for specialized Full-Stack & Cloud Engineers"],
            ["Fiverr", "Packaged fixed-price gigs (e.g., 'I will build a React dashboard')", "$150 – $1,500+ per standardized deliverable tier"],
            ["Toptal / Turing", "Elite global remote engineering retainers (Rigorous technical exam entry)", "$60 – $120+ / hr with guaranteed full-time corporate matching"],
            ["Direct LinkedIn Consulting", "B2B cold outreach to engineering founders and CTOs", "Custom project retainers ($3,000 – $10,000+ per project milestone)"]
          ]
        ),
        "",
        "## 6. Interactive Freelance Contract Checklist",
        "",
        H.buildChecklist("Freelance Job Protection Audit", [
          { label: "Payment Method Verified by Platform", desc: "Client's billing status shows green verified checkmark before accepting contract invitation." },
          { label: "Escrow Milestone Funded", desc: "100% of Milestone 1 budget is actively deposited in platform escrow before writing any code." },
          { label: "All Communications on Platform", desc: "All scope discussions and file transfers occur inside Upwork/Fiverr messenger for legal arbitration trail." },
          { label: "Scope of Work (SOW) Explicitly Written", desc: "Exact number of revisions, pages, and API endpoints are listed in contract terms to prevent scope creep." }
        ]),
        "",
        H.buildClosingPage(title)
      ].join("\n");
    }

    // 16. Career Planning Workbook
    if (titleLower.includes("career planning") || titleLower.includes("workbook") || catLower.includes("workbook") || catLower.includes("planning")) {
      return [
        H.buildCoverPage("CorpersTech 1-Year NYSC Career Transition Workbook", "Your Personalized 12-Month Roadmap from NYSC Corp Member to High-Earning Tech Professional", "Career Planning & Workbooks"),
        H.buildTableOfContents([
          { id: "1-personal-brand--skill-gap-audit", title: "Personal Brand & Skill Gap Audit" },
          { id: "2-quarterly-nysc-execution-milestones", title: "Quarterly NYSC Execution Milestones (Q1–Q4)" },
          { id: "3-weekly-applicant-tracking-ledger", title: "Weekly Applicant Tracking Ledger" },
          { id: "4-salary-negotiation--benchmarking-framework", title: "Salary Negotiation & Benchmarking Framework" },
          { id: "5-interactive-12-month-transition-checklist", title: "Interactive 12-Month Transition Checklist" },
          { id: "6-closing-advice-learning-path--contact", title: "Closing Advice, Learning Path & Contact" }
        ]),
        "## 1. Personal Brand & Skill Gap Audit",
        "",
        "*Complete this worksheet during Week 1 of your Olatech School of Programming enrollment.*",
        "",
        "### 1. Current Baseline vs. Target Role.",
        "* **My Current Degree / Background:** __________________________________________________",
        "* **My Target Tech Role (e.g., Full-Stack Engineer, SOC Analyst, Data BI Specialist):** __________________________________________________",
        "* **Target Post-NYSC Monthly Compensation Goal:** ₦_____________________ / $_____________________",
        "",
        "### 2. Core Skill Gap Matrix.",
        "List 3 skills required for your target job postings that you currently lack:",
        "1. **Technical Skill 1:** __________________________ | **How I will learn it:** [ ] Olatech Bootcamp [ ] Labs [ ] Documentation",
        "2. **Technical Skill 2:** __________________________ | **How I will learn it:** [ ] Olatech Bootcamp [ ] Labs [ ] Documentation",
        "3. **Technical Skill 3:** __________________________ | **How I will learn it:** [ ] Olatech Bootcamp [ ] Labs [ ] Documentation",
        "",
        "---",
        "",
        "## 2. Quarterly NYSC Execution Milestones (Q1–Q4)",
        "",
        "### Q1 (Months 1 – 3): Foundation & Core Bootcamp Mastery.",
        "* [ ] Complete 100% of Olatech School of Programming core lectures and live coding labs.",
        "* [ ] Build and deploy at least **2 solo mini-projects** to GitHub with professional Markdown READMEs.",
        "* [ ] Create and optimize my LinkedIn professional headline and About summary section.",
        "* [ ] Attend at least 2 institutional mentorship career advisory sessions.",
        "",
        "### Q2 (Months 4 – 6): Capstone Project & Portfolio Launch.",
        "* [ ] Collaborate with a cross-functional student team to build a production-grade **Capstone Web Application**.",
        "* [ ] Deploy the application live (Google Cloud Run / Vercel) and connect a custom domain name.",
        "* [ ] Write a detailed technical case study article on LinkedIn or Medium breaking down the architecture of my capstone project.",
        "* [ ] Prepare my 1-page ATS-optimized Word/PDF Resume following the Olatech XYZ bullet formula.",
        "",
        "### Q3 (Months 7 – 9): Intensive Placement & Interview Sprints.",
        "* [ ] Execute a weekly application routine: submit **10 tailored job proposals/applications** per week.",
        "* [ ] Complete 3 live mock technical coding or system design interviews with Olatech Career Placement Officers.",
        "* [ ] Reach out to 5 engineering recruiters or senior engineers per week on LinkedIn using personalized networking scripts.",
        "* [ ] Participate in at least 1 external hackathon or open-source software contribution sprint.",
        "",
        "### Q4 (Months 10 – 12): Offer Negotiation & Post-NYSC Transition.",
        "* [ ] Evaluate incoming job offers or contract retainers against Olatech placement benchmark standards.",
        "* [ ] Consult with Placement Officers on salary negotiation scripts and corporate benefits packages.",
        "* [ ] Execute final PPA exit clearance and request official institutional recommendation letters.",
        "* [ ] Transition smoothly into full-time employment or senior freelance consultancy!",
        "",
        "---",
        "",
        "## 3. Weekly Applicant Tracking Ledger",
        "",
        "*Use this table to track your active job applications during Q3 & Q4:*",
        "",
        "| Date Applied | Company Name | Role Title | Application URL / Portal | Contact Person / Recruiter | Current Status (Applied/Interview/Offer) | Follow-Up Date |",
        "| :--- | :--- | :--- | :--- | :--- | :--- | :--- |",
        "| ____/____/2026 | ____________ | ____________ | ________________________ | __________________________ | ________________________________________ | ____/____/2026 |",
        "| ____/____/2026 | ____________ | ____________ | ________________________ | __________________________ | ________________________________________ | ____/____/2026 |",
        "| ____/____/2026 | ____________ | ____________ | ________________________ | __________________________ | ________________________________________ | ____/____/2026 |",
        "| ____/____/2026 | ____________ | ____________ | ________________________ | __________________________ | ________________________________________ | ____/____/2026 |",
        "| ____/____/2026 | ____________ | ____________ | ________________________ | __________________________ | ________________________________________ | ____/____/2026 |",
        "",
        "---",
        "",
        "## 4. Salary Negotiation & Benchmarking Framework",
        "",
        "Never accept the first salary offer without polite, professional negotiation. Use this script when receiving an initial offer:",
        "",
        "> *\"Thank you so much for extending this offer! I am thrilled about the opportunity to join the engineering team at [Company Name]. Based on my specialized training at Olatech School of Programming, my deployed full-stack capstone portfolio, and current market compensation benchmarks for this role, I was hoping we could explore an entry compensation closer to [Target Salary]. Would there be flexibility to adjust the base compensation or professional development allowance to bridge that gap?\"*",
        "",
        "---",
        "",
        "## 5. Interactive 12-Month Transition Checklist",
        "",
        H.buildChecklist("Annual Career Transition Assurance", [
          { label: "Q1 Foundation Milestones Complete", desc: "Core coding bootcamps finished and two solo mini-projects deployed to GitHub." },
          { label: "Q2 Capstone Application Live", desc: "Full-stack capstone project running on custom domain with comprehensive technical case study published." },
          { label: "Q3 Application Sprints Active", desc: "Submitted at least 40 tailored job applications and completed three institutional mock interviews." },
          { label: "Q4 Placement Offer Validated", desc: "Received and reviewed employment contract with Olatech Placement Officer before signing." }
        ]),
        "",
        H.buildClosingPage(title)
      ].join("\n");
    }

    return null;
  }
}
