export const STAFF_HANDBOOK_PART_5 = `# 14. Frequently Asked Questions (50+ Comprehensive Staff Q&As)

This chapter addresses over 50 realistic, practical questions frequently asked by new and experienced staff members across all Olatech School of Programming departments. Use this exhaustive reference to troubleshoot daily operational challenges.

---

### Q1: I am a new employee and just received my temporary login credentials. When I attempt to log into the Command Center, I receive an "Invalid Account State" error. What should I do?
**Answer**: An "Invalid Account State" error indicates that your supervisor (Super Admin) has provisioned your account in the database but has not yet assigned an active Role-Based Access Control (RBAC) scope, or your account flag is currently set to *Suspended/Inactive*. Do not attempt multiple repeated logins as this may trigger IP rate-limiting. Contact the Super Admin or Support Lead immediately via official internal chat to verify that your account status is toggled to *Active* and your role scope (e.g., *Admissions Officer*, *Career Officer*) is properly bound to your corporate email address.

### Q2: How often am I required to change my Command Center password, and what happens if I forget it while working remotely?
**Answer**: Institutional security policy mandates password rotation every **90 days**. The system will display a countdown banner 7 days prior to expiration. If you forget your password or become locked out while working remotely, click the *"Forgot Password / Staff Support"* link on the login portal. This generates an encrypted, time-sensitive reset token sent to your official \`@olatechschool.com\` email address. If you cannot access your corporate email, you must contact the Super Admin via telephone for manual identity verification and administrative reset.

### Q3: Why does the CorpersTech Command Center automatically log me out after 30 minutes, and can I disable this feature for my instructor terminal?
**Answer**: The 30-minute idle timeout is a mandatory security control enforced across all role levels to prevent unauthorized access to sensitive student Personal Identifiable Information (PII) on unattended workstations. This feature is hardcoded into the platform's authentication middleware and **cannot be disabled or bypassed** by individual staff members or instructors. Always save your active work and explicitly log out if leaving your terminal.

### Q4: When reviewing an incoming student application in the Admissions Module, how do I verify the authenticity of an NYSC Call-Up Letter number?
**Answer**: In the Admissions Enrollee table, click on the applicant's record to open their comprehensive dossier. Locate the submitted NYSC Call-Up Letter number (typically formatted as \`NYSC/FCT/2026/001234\`). Open the official institutional verification portal link embedded in the admissions dashboard, which cross-references the call-up number against official NYSC state deployment master lists. Ensure the applicant's full name, state of origin, and PPA match the state deployment manifest exactly before toggling the *Documents Verified* checkbox.

### Q5: What is the exact procedure if an enrollee's academic degree certificate appears fraudulent, altered, or unreadable?
**Answer**: Never approve an enrollee with dubious academic documentation. If a document is unreadable due to low scanner resolution, update the applicant's status to *Pending* and use the CRM messaging tool to send a standardized document re-upload request. If you suspect intentional alteration or fraud (e.g., mismatched font typography, manipulated university seals), flag the application as *Under Investigation*, append a detailed administrative observation note in the audit trail, and escalate the dossier directly to the Admissions Lead and Executive Director for formal disqualification review.

### Q6: Can an Admissions Officer delete a rejected or duplicate student application from the Command Center database?
**Answer**: **No.** To preserve strict institutional audit integrity and prevent historical data manipulation, Admissions Officers do not possess hard-deletion permissions. If an applicant submits a duplicate enrollment form or is permanently rejected, transition the record status to *Rejected* or *Archived*, and append an explanatory note. Only the Super Admin possesses the permission to execute permanent database purging during scheduled system maintenance windows.

### Q7: Explain the exact workflow of the 6-Point Vetting Checklist in the Admissions Module. Why must all 6 points be checked before final enrollment?
**Answer**: The 6-Point Checklist is our administrative quality gate. The points represent mandatory institutional prerequisites: (1) **Docs**: NYSC call-up letter and degree verified; (2) **Laptop**: Confirmation that the student owns or has secured institutional hardware access; (3) **Pay**: Verification of tuition payment or NYSC scholarship fee-waiver attachment; (4) **Orient**: Completion of mandatory onboarding orientation webinar; (5) **WhatsApp**: Confirmed addition to the official cohort communication group; and (6) **Ready**: Final administrative clearance. Checking all 6 points ensures the student is 100% prepared for classroom immersion, preventing downstream disruption in teaching labs or transport shuttles.

### Q8: What should I do if an applicant claims they were granted a 100% Executive Scholarship by the State Coordinator but their payment status shows "Unpaid"?
**Answer**: Do not take verbal claims or unverified email forwards as proof of scholarship allocation. Request the official, signed NYSC State Coordinator Scholarship Allocation Letter from the student. Once received, contact the Finance Officer to cross-reference the document against the master scholarship authorization ledger. When the Finance Officer confirms validity, they will apply the *Scholarship Fee-Waiver* badge in the database, automatically updating the financial clearance flag in your admissions checklist.

### Q9: Why does the AI Recruitment Scraper assign confidence scores to harvested job openings, and what do percentages like 45% vs 92% indicate?
**Answer**: The automated web scraper harvests vacancies from public job boards where scam postings, commission-only MLM schemes, and outdated advertisements proliferate. Our integrated Google Gemini AI engine analyzes the scraped job description syntax, company domain legitimacy, email contact professionalism, and salary transparency to generate a **Confidence Score (0–100%)**. A score of **92%** indicates a highly legitimate, well-structured tech vacancy from a verified corporate domain. A score of **45%** indicates red flags (e.g., requesting application fees, missing company name, vague job duties), prompting immediate quarantine and rejection by Career Officers.

### Q10: How do I manually trigger the AI Discovery Engine to scrape new job opportunities if a graduating cohort needs immediate placement?
**Answer**: Log into the Command Center as a Career Officer or Super Admin and navigate to **Module 3 (Recruitment AI)**. Locate the *Discovery Engine Controls* panel at the top right of the dashboard. Click the **\`[Run AI Discovery Scan]\`** button. You can select specific target sources (e.g., *LinkedIn Nigeria*, *Jobberman*, *MyJobMag*, *Remote.co*) or run a global sweep. The engine will execute asynchronously in the background, harvesting new DOM nodes, scoring vacancies via Gemini AI, and populating the *Unverified Scraped Opportunities* queue within 60 to 120 seconds.

### Q11: What is the mandatory 4-Tier Vacancy Verification Workflow that Career Officers must execute before publishing a job to students?
**Answer**: To protect students from exploitation, every harvested vacancy must traverse four strict verification tiers:
1. **Tier 1 (AI Filtering)**: Automated engine purges scores below 60%.
2. **Tier 2 (Metadata Scrubbing)**: Career Officer reviews title, required tech stack tags (*React, Node, Python*), and removes recruiter spam formatting.
3. **Tier 3 (Employer Verification)**: Officer verifies company existence via CAC registry checks, LinkedIn company page auditing, or direct telephone/email contact with HR.
4. **Tier 4 (Final Approval & Publication)**: Officer toggles status from *Under Review* to *Verified & Approved*, enabling the **\`[Publish to Student Hub]\`** action.

### Q12: How does the Opportunity Duplicate Detector work, and what should I do if two identical job postings from different scrapers appear in the queue?
**Answer**: The CorpersTech AI engine runs semantic similarity algorithms across scraped job titles, company names, and description body strings. When identical or near-identical vacancies appear (e.g., a role posted simultaneously on LinkedIn and Jobberman), the system flags the secondary posting in the **Opportunity Duplicate History** log. Career Officers should review the duplicate pair, merge any unique contact metadata into the primary record, and click **\`[Archive Duplicate]\`** to maintain a clean, uncluttered Opportunity Board for students.

### Q13: A corporate hiring partner wants to hire 5 React developers exclusively from Olatech. How do I bypass the public scraper and publish an exclusive internal role?
**Answer**: Navigate to the **Career Launch Hub (Module 2)** and click **\`[+ Create Manual Opportunity]\`**. Fill out the comprehensive vacancy form: enter the corporate employer's details, select the category (*Full-Stack Engineering*), set the opportunity source to *Direct Employer Partner*, input the salary range, and toggle the visibility badge to **\`[Exclusive Olatech Partner Role]\`**. Upon saving, this role bypasses scraper queues and is published immediately with a high-priority star badge on the student dashboard.

### Q14: How does the AI CV Evaluator work, and how should Career Officers utilize its scoring output during student mentorship sessions?
**Answer**: The AI CV Evaluator allows students to paste their resume text and target job role into an interactive analysis portal. Google Gemini AI evaluates the text against real-world tech recruitment standards, generating a composite score (0–100%) and 4 detailed analytical breakdowns: *Keyword Optimization*, *Project Impact Metrics*, *Formatting & Clarity*, and *Action Verb Strength*. During 1-on-1 mentorship sessions, Career Officers should pull up the student's CV evaluation report in the dashboard and guide them through implementing the AI's specific bullet-point improvement suggestions before submitting job applications.

### Q15: Why is the Student Transportation Module integrated directly into the Command Center instead of being managed by drivers on external WhatsApp groups?
**Answer**: External WhatsApp groups provide zero accountability, lead to severe bus overcrowding, and make financial fuel auditing impossible. By integrating transportation directly into CorpersTech, student bus route assignments are bound to their verified enrollment profiles. The platform generates real-time seat manifests, tracks exact passenger counts per route (e.g., *Yaba Hub - 42/45 seats filled*), prevents unauthorized non-enrollees from boarding, and provides immutable audit records for vendor fuel and vehicle lease disbursements.

### Q16: How do I generate and print a physical bus boarding manifest for a morning shuttle route experiencing heavy passenger volume?
**Answer**: Navigate to **Module 4 (Transportation & Logistics)**. In the active routes dashboard, select the specific bus route (e.g., *Abuja Garki CBD Express - Bus #3*). Click the **\`[Export Boarding Manifest]\`** button. The system compiles an alpha-sorted HTML print table containing student full names, enrollee IDs, phone numbers, emergency contacts, and boarding signature boxes. Click **\`[Print Manifest]\`** to invoke the system print dialog and print physical A4 sheets for the bus captain or driver.

### Q17: What happens if a shuttle bus breaks down in transit between Victoria Island and mainland Lagos during morning peak hours?
**Answer**: Execute the **Emergency Transit Breakdown SOP**: (1) The bus driver immediately notifies the Operations Officer via phone/radio; (2) The Operations Officer opens the Transportation Dashboard, locates the affected vehicle, and clicks **\`[Trigger Route Emergency]\`**; (3) The system automatically broadcasts an urgent SMS/WhatsApp alert to all affected passengers on that manifest advising them of a rescue bus dispatch; (4) The Operations Officer dispatches the nearest on-standby rescue shuttle van and logs the maintenance incident in the vehicle asset registry.

### Q18: Can a student change their daily bus pickup location mid-semester, and how does this affect route capacity calculations?
**Answer**: Students cannot arbitrarily change bus routes without administrative authorization, as this destabilizes seat capacity calculations. If a corps member relocates their PPA or residence, they must submit a formal *Route Transfer Request* via the student helpdesk. The Operations Officer reviews active route capacities in Module 4; if the target route has available seating (e.g., below 100% capacity), the officer updates the student's transportation preference field in their CRM dossier, which automatically reallocates seat counts across both manifests.

### Q19: In the Operations Center (Module 5), why do the live statistics sometimes differ slightly from external Google Analytics website visitor counts?
**Answer**: External Google Analytics tracks raw browser HTTP requests and anonymous landing page sessions, including web crawlers and bounced visitors. The **Operations Center Live Statistics** dashboard compiles authenticated, highly accurate database records directly from Prisma models (e.g., exact count of verified enrolled students, active staff accounts, published job vacancies, and logged-in learning sessions). Always rely on the Operations Center database metrics for official institutional reporting and board presentations.

### Q20: How should staff members handle incoming public contact inquiries and complaints received in the Operations Enquiry Inbox?
**Answer**: The Operations Enquiry Inbox aggregates messages submitted via the public contact form and support email aliases. Staff must review the inbox twice daily (morning and afternoon). Click an enquiry to open the response thread. If the query is a basic admissions question, reply directly using standardized templates. If the inquiry involves a technical lab glitch or financial dispute, assign the ticket to the respective departmental lead (*Support Officer* or *Finance Officer*) using the dropdown assignment menu, ensuring an SLA response within 24 hours.

### Q21: What is the purpose of the Olatech Documentation Center (Module 6), and why is it referred to as a "Gold Master Repository"?
**Answer**: The Documentation Center is our definitive institutional knowledge base. It is designated a **Gold Master Repository** because every handbook, standard operating procedure (SOP), and training manual published within it undergoes rigorous executive review and checksum verification. It serves as the single source of truth for staff onboarding, operational compliance, and student rules. Never rely on informal word-of-mouth instructions or outdated printed pamphlets; if an instruction is not documented in the Gold Master repository, it is not official institutional policy.

### Q22: When reading a document in the Documentation Center, what do the "Bookmark" and "Mark as Read" buttons do?
**Answer**: The **\`[Bookmark]\`** button saves the specific handbook or operational manual to your personal *Quick Access Toolbar* at the top of the documentation screen, allowing instant one-click retrieval during daily operations. The **\`[Mark as Read]\`** button logs an immutable timestamped record in the **Staff Document Reading History** database (\`staffDocumentReading\` model). Supervisors and Super Admins monitor reading history reports to confirm that new employees have completed mandatory onboarding handbook readings during their first week of employment.

### Q23: How does the Feedback & Suggestion system in the Documentation Center work, and who reviews staff suggestions?
**Answer**: At the bottom of every published handbook view, staff members can submit structured feedback: assigning a 1-to-5 star utility rating, toggling *Outdated Content* flags, and typing specific improvement suggestions. This feedback is written directly to the \`staffDocumentFeedback\` database registry. At the end of each month, the Super Admin and Department Leads review the feedback analytics dashboard, prioritize flagged manuals for revision, and release updated version increments (e.g., upgrading Version 1.0 to Version 1.1).

### Q24: What is the exact difference between clicking "[Download Markdown]" and clicking "[Print / Export PDF]" in the Documentation Center?
**Answer**:
* **\`[Download Markdown]\`**: Exports the raw, unformatted \`.md\` text file of the handbook directly to your local workstation. This is ideal for software engineers, instructors, or staff who wish to read documentation offline in code editors like VS Code or Obsidian, or who need to grep for specific operational terms across files.
* **\`[Print / Export PDF]\`**: Invokes the CorpersTech Gold Master Print Engine. The system parses the Markdown into a beautifully styled, high-contrast HTML document with exact A4 print margins (\`25mm 20mm\`), professional typography, table borders, and running headers, then automatically triggers your browser's native print dialog where you can select **"Save as PDF"** to generate a publication-grade, multi-page corporate manual.

### Q25: Why does the browser open a print preview dialog when I click to download the PDF handbook instead of saving a .pdf file directly?
**Answer**: To maintain a clean, lightweight, and dependency-free backend architecture without relying on heavy, vulnerable third-party Node binary PDF rendering libraries (like Puppeteer or wkhtmltopdf), CorpersTech utilizes a **Client-Side Gold Master Print-to-PDF compilation engine**. The browser's native rendering engine is the most powerful HTML/CSS layout tool available; by opening a dedicated print window formatted with strict CSS \`@page\` rules and invoking \`window.print()\`, we ensure pixel-perfect vector typography, perfect page breaks, and zero server CPU overhead.

### Q26: How do I ensure that when I export this Staff Handbook to PDF, it doesn't print with awkward blank pages or cut off tables mid-row?
**Answer**: Our CSS print stylesheet is explicitly optimized with page-break integrity rules: \`page-break-inside: avoid;\` is applied to all tables, ASCII organizational charts, warning boxes, and section headers (\`h1, h2, h3\`). When the print preview dialog opens in Google Chrome, Microsoft Edge, or Apple Safari, ensure that your print settings are configured to: (1) **Paper Size: A4**; (2) **Margins: Default or Custom (25mm top/bottom, 20mm sides)**; (3) **Background Graphics: Checked/Enabled**; and (4) **Scale: 100%**. This guarantees a clean 40–60 page publication output.

### Q27: What is the Backup Center (Module 7), and who has the administrative permission to generate or download system database snapshots?
**Answer**: The Backup Center is our disaster recovery command module. It compiles all live relational database models (Enrollments, Staff, Job Opportunities, Applications, Documents, Audit Logs) into a structured, downloadable JSON snapshot file. **Only the Super Admin (Level 5 Authority)** possesses the permission to access Module 7, generate backups, or execute database restoration protocols. Any attempt by Level 2 or Level 3 staff to access backup URL endpoints is blocked by RBAC middleware and logged as a security alert.

### Q28: What is the difference between a "Raw JSON Snapshot" and a "Verified Checksum Backup" in the Backup Center?
**Answer**: A **Raw JSON Snapshot** is a direct dump of database table rows without structural validation. A **Verified Checksum Backup** undergoes automated pre-archival verification by the CorpersTech Backup Engine: the system scans the exported JSON to confirm that JSON syntax is valid, all required primary keys exist, foreign key relationships (e.g., \`jobApplication.opportunityId -> jobOpportunity.id\`) are intact, and calculates a cryptographic SHA-256 checksum hash. Only verified checksum backups are certified for disaster recovery restoration.

### Q29: If an accidental mass deletion occurs in the student database, explain the exact step-by-step procedure to execute a rollback restore.
**Answer**: (1) The Super Admin immediately navigates to **Module 7 (Backup Center)**; (2) Under the *Disaster Recovery & Rollback* section, click **\`[Upload & Restore Backup]\`** or select the latest timestamped verified backup from the server archive list; (3) The system displays a confirmation warning modal detailing the records to be overwritten; (4) Enter the Super Admin confirmation authorization code and click **\`[Execute Rollback]\`**; (5) The backend database engine suspends foreign key checks, purges corrupted tables, repopulates all records from the snapshot, re-enables constraints, and displays a success confirmation banner within 5 seconds.

### Q30: How does the CorpersTech platform function during an internet outage when the primary cloud PostgreSQL/MySQL database becomes unreachable?
**Answer**: CorpersTech is engineered with an **Offline JSON Fallback Architecture**. When the Node.js Express server attempts a Prisma ORM database query and catches a network connection timeout or offline error, it transparently intercepts the request and reroutes read/write operations to local persistent JSON file stores located on the server filesystem (e.g., \`docs-fallback-db.json\`, \`staff-fallback.json\`). This ensures that campus workstations and offline command center terminals never crash, allowing staff to continue onboarding students and reviewing manuals seamlessly during grid outages.

### Q31: When internet connectivity is restored after an offline fallback period, how do local JSON mutations synchronize back with the cloud database?
**Answer**: Once network monitors detect that the primary cloud Prisma database is reachable, the automated **Recruitment & Operational Intelligence Sync Engine** executes a background reconciliation cycle. It compares timestamps between local JSON fallback records and cloud database rows, safely pushing queued local enrollments, administrative notes, and newly harvested job opportunities into the primary relational database while logging all synchronization events in the system audit trail.

### Q32: Why is the audit log ticker displayed permanently at the bottom of the Command Center dashboard, and can staff hide it?
**Answer**: The permanent streaming **Audit Log Banner** is a deliberate architectural feature designed to promote institutional transparency, peer accountability, and security awareness. By displaying real-time system actions (e.g., *"Admissions Lead updated Enrollee #12 to Approved"*, *"Career Officer published 4 new vacancies"*), all staff remain synchronized with campus operations. This banner is an integral UI component and **cannot be hidden or closed** by administrative users.

### Q33: How do I export a monthly demographic report of enrolled NYSC corps members for presentation to the State Secretariat?
**Answer**: Navigate to **Module 8 (Reports & Analytics)**. Under the *Demographic & Intake Analytics* section, select your target reporting timeframe (e.g., *Current Month* or *2026 Batch B Stream I*). Review the interactive charts showing state of origin distribution, gender ratios, and course enrollments. Click the **\`[Export Demographic CSV]\`** or **\`[Generate Printable Executive Report]\`** button. The system compiles the dataset into a clean spreadsheet or formatted print summary formatted specifically for NYSC state coordination officials.

### Q34: What is the procedure if a staff member suspects that an external job vacancy harvested by the AI scraper is actually a phishing scam?
**Answer**: If a harvested vacancy appears suspicious (e.g., requesting applicants to pay for "training materials" or click obscure shortened links), a Career Officer must immediately click the **\`[Quarantine / Reject]\`** action button on the opportunity card. This removes the vacancy from public student view, tags the source domain in the automated scraper blacklist, and logs a security observation note. Never attempt to test suspicious links on institutional computers.

### Q35: How does the Settings & RBAC Module (Module 9) prevent unauthorized escalation of administrative privileges?
**Answer**: Module 9 enforces strict cryptographic privilege separation. Staff accounts are assigned fixed role enumerations (\`Super Admin\`, \`Admissions Officer\`, \`Career Officer\`, \`Operations Officer\`, \`Finance Officer\`, \`Support Officer\`). The backend Express API routes are protected by role-verification middleware that inspects authenticated JWT session tokens on every HTTP request. If a Level 3 Admissions Officer attempts to send a POST request to an endpoint reserved for Level 5 Super Admins (such as database restoration or staff salary modification), the API returns an immediate \`403 Forbidden\` error and records a potential breach alert in the audit log.

### Q36: What should an Admissions Officer do if an applicant's NYSC PPA is located in a remote local government without company shuttle bus coverage?
**Answer**: During the 6-Point Vetting Checklist review, check the applicant's indicated PPA and residential landmark against active bus routes in the Transportation Module. If the student resides outside shuttle coverage (e.g., remote border towns in FCT or Lagos outskirts), advise the student during the orientation call that they will need to utilize independent transportation or join online weekend virtual lab sessions. Update the *Transportation Option* field in their CRM profile to **"Individual Transportation / Virtual Access"** so they are not erroneously added to physical bus boarding manifests.

### Q37: How do Career Officers utilize the Project Showcase Module to attract corporate hiring partners?
**Answer**: When students complete their final Full-Stack Web Development, Data Science, or AI capstone projects, instructors submit their GitHub repositories and live demo URLs to the Career Officer. The officer reviews the code quality, formats a professional summary, and publishes the project in the **Project Showcase Gallery** (within Module 2). When corporate hiring partners visit the CorpersTech portal seeking engineering talent, Career Officers direct them to this interactive gallery where employers can test live student applications and request immediate hiring interviews.

### Q38: Why is it strictly prohibited for staff members to accept personal cash payments or direct bank transfers from corps members for tuition or laptops?
**Answer**: To eliminate financial fraud, bribery, and audit discrepancies, Olatech School of Programming operates a **Strict Cashless & Direct-Gateway Policy**. All tuition fees, laptop installments, and textbook purchases must be processed through official institutional bank accounts or authenticated online payment gateways integrated into the student portal. Any staff member found accepting cash, personal bank transfers, or informal point-of-sale (POS) payments from students will face immediate termination and criminal prosecution for financial defalcation.

### Q39: What is the exact procedure when a staff member resigns or is terminated from Olatech School of Programming?
**Answer**: Execute the **Employee Offboarding & Access Revocation SOP**: (1) On the effective date of departure, the Super Admin logs into **Module 9 (Settings & RBAC)**; (2) Locate the departing employee's account in the staff directory; (3) Toggle account status from *Active* to **\`[Deactivated / Revoked]\`** and scramble their password hash; (4) Terminate all active JWT browser sessions; (5) Remove the employee from all internal Slack/Discord channels and official WhatsApp student broadcast groups; (6) Retrieve and wipe all institutional hardware (laptops, access badges, campus keys) and log the completed offboarding checklist in the audit trail.

### Q40: How do I ensure that this enhanced Olatech Staff Handbook is always accessible to new staff during onboarding?
**Answer**: This Gold Master handbook is permanently compiled into the backend database and pinned as **Document ID #1** in the institutional repository (\`src/server/repositories/DocumentRepository.ts\`). It is also mapped directly to the **\`[Olatech Staff Handbook]\`** button in the Quick Downloads side list of the CorpersTech Documentation Center (\`/docs\`). On their very first day of orientation, every new hire must be instructed to open Module 6, click this exact download button, read the manual in its entirety, and execute the final onboarding compliance sign-off.

### Q41: Explain how the AI Scraper Change Log monitors modifications to external job postings over time.
**Answer**: External employers frequently modify active job advertisements—changing salary ranges, altering application deadlines, or updating remote work policies. The CorpersTech AI Scraper runs daily re-indexing cycles on previously harvested vacancies. When the scraper detects a DOM string discrepancy between the live web page and our database record, it records the exact delta in the **Opportunity Change Log** (\`opportunityChangeLog\` model), highlighting whether the salary was increased/decreased or if the application deadline was extended. Career Officers review this change log daily to ensure student job alerts remain 100% accurate.

### Q42: What should an Operations Officer do if the campus diesel generator fails to start during a primary power grid outage?
**Answer**: Execute the **Generator Failure Emergency Protocol**: (1) Immediately contact the contracted generator maintenance engineering vendor on their emergency SLA hotline; (2) Instruct campus lab assistants to verify that the secondary 20kVA inverter battery banks are actively carrying the workstation power load; (3) If generator repairs will exceed battery backup duration (approx. 4 hours), notify instructors to transition physical classroom sessions to asynchronous local project work or reschedule the afternoon lab block; (4) Log the equipment failure and vendor response time in the Operations Facility Incident Ledger.

### Q43: How does the Finance Officer audit vendor invoices submitted for student transportation shuttle fuel and maintenance?
**Answer**: Transport contractors submit weekly invoices detailing bus license plates, routes served, total kilometers driven, and fuel receipts. The Finance Officer logs into **Module 4 (Transportation)** and exports the weekly driver manifests and GPS route distance logs. Cross-reference the contractor's billed kilometers and departure frequencies against official Command Center manifest records. Only approve vendor disbursements when manifest passenger counts and route logs match the submitted invoice within a 2% margin of error.

### Q44: What is the procedure for an Admissions Officer when an enrollee requests a defermat of their admission to the next NYSC batch?
**Answer**: If a corps member is redeployed to another state by NYSC authorities or faces severe personal circumstances, they may request admission deferral. The Admissions Officer must: (1) Request a copy of the official NYSC Redeployment Letter or medical document; (2) Locate the student's record in the Admissions table; (3) Update the enrollment status from *Approved/Enrolled* to **\`[Deferred]\`**; (4) Append an administrative note specifying the target future cohort (e.g., *"Deferred from 2026 Batch A Stream II to 2026 Batch B Stream I due to NYSC state redeployment"*); (5) Notify the Finance Officer to freeze any paid tuition credits for future cohort redemption.

### Q45: How can Support Officers identify if a student's login failure is caused by a forgotten password versus a browser caching/local storage error?
**Answer**: When a student reports a login failure, first check their account status in the Support/Admissions dashboard. If their account shows *Active* and no failed login lockouts are recorded in the server console, the issue is almost certainly local browser caching or stale JWT storage. Instruct the student to perform a **Hard Refresh** (\`Ctrl + F5\` on Windows, \`Cmd + Shift + R\` on macOS) or attempt logging in via an Incognito/Private browsing window. If Incognito login succeeds, guide the student to clear their browser site data and cookies for the CorpersTech domain.

### Q46: What is the "Opportunity Source Registry" in Module 3, and how do Career Officers add a brand new tech job board to the AI scraper seed list?
**Answer**: The **Opportunity Source Registry** (\`opportunitySource\` model) manages the seed URLs and scraping rules for external job boards. To add a new source (e.g., a newly launched African remote tech job portal): (1) Navigate to Module 3 and open the *Source Registry* tab; (2) Click **\`[+ Add Opportunity Source]\`**; (3) Enter the portal name, base URL, scraper frequency interval (e.g., *Every 12 Hours*), and target CSS selector tags for vacancy containers; (4) Set status to *Active*; (5) Trigger a test discovery run to verify that the AI engine can successfully parse and score vacancies from the new domain.

### Q47: How should staff members handle visits from official NYSC State Secretariat monitoring officials or inspectors arriving on campus?
**Answer**: NYSC monitoring officials conduct periodic unannounced inspections of training facilities and student attendance. When inspectors arrive: (1) Receive them with utmost courtesy and conduct them immediately to the Executive Director or Operations Lead office; (2) Open the **Operations Center (Module 5)** and generate an instant, authenticated report showing total enrolled corps members, active classroom attendance, and PPA clearance manifests; (3) Conduct the officials on a guided tour of the physical coding labs, showcasing students actively working on technical projects; (4) Provide physical printed copies of our institutional handbooks and executive summaries upon request.

### Q48: Why does the CorpersTech database utilize soft-deletion flags (e.g., isDeleted: true) for staff and student records instead of permanent SQL DROP or DELETE statements?
**Answer**: In enterprise educational and financial systems, permanent SQL deletion destroys historical referential integrity and violates statutory audit trail requirements. For example, if a staff member who approved 500 admissions records is permanently deleted from the database, all 500 student records would lose their audit trail foreign key reference. By utilizing **Soft-Deletion Flags** (\`isDeleted: true\`, \`status: 'Archived'\`), records are hidden from active daily operational views and login authentication while remaining permanently preserved in relational database history for statutory audits and forensic investigations.

### Q49: How can instructors and staff members participate in contributing new chapters or technical updates to the CorpersTech Documentation Center?
**Answer**: Olatech promotes an open, collaborative documentation culture. If an instructor or staff member develops a new teaching methodology, debugging guide, or operational SOP: (1) Draft the document in clean, structured Markdown format; (2) Submit the draft to the department lead for technical peer review; (3) Once approved, the department lead or Super Admin accesses **Module 6 (Documentation Center)**, clicks **\`[+ Add Manual / Handbook]\`**, pastes the Markdown content, assigns appropriate category tags and role visibility scopes, and publishes the certified manual directly into the live Gold Master repository.

### Q50: Why is this Olatech Staff Handbook designated as "Version 1.0 Gold Master", and what does "Gold Master" certification represent in software and institutional engineering?
**Answer**: In software engineering and institutional governance, a **Gold Master (GM)** designation represents the definitive, certified, publication-grade release candidate that has passed all rigorous quality assurance, checksum verification, and executive auditing. By certifying this handbook as **Version 1.0 Gold Master**, Olatech School of Programming declares that every policy, workflow, and technical specification documented herein has been fully tested, validated against real-world campus operations, integrated into the CorpersTech command backend, and approved by executive leadership as our binding institutional operational law.
`;